project_id         = "c3b-sandbox-dev"
region             = "australia-southeast2"
scheduler_region   = "australia-southeast1"
chat_space_name    = "spaces/AAQArTTIdxc"
scheduler_cron     = "0 9 * * 1-5"
scheduler_timezone = "Pacific/Auckland"
