project_id         = "YOUR_PROD_PROJECT_ID"
region             = "us-central1"
chat_space_name    = "spaces/YOUR_PROD_SPACE_ID"
scheduler_cron     = "0 9 * * 1-5"
scheduler_timezone = "America/New_York"
